global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "ledger-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ledger-service:8080"]

  - job_name: "projection-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["projection-service:8081"]
